<?xml version="1.0" encoding="UTF-8"?>
<!-- Nuevo xml con el elemento agenda 
que contenga contactos con: Nombre, Correo, Teléfono -->

<!-- Modificad el doctype y las etiquetas 
para incluir el atributo genero en los contactos -->

<!-- Validación de estructura de nuestro XML -->
<!DOCTYPE agenda[
    <!ELEMENT agenda (contacto+)>
    <!ELEMENT contacto (nombre, correo, telefono)>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT correo (#PCDATA)>
    <!ELEMENT telefono (#PCDATA)>
    <!ATTLIST telefono prefijo CDATA #REQUIRED>
    <!ATTLIST contacto genero CDATA #REQUIRED>
]>

<agenda>
    <contacto>
        <nombre>Pepe</nombre>
        <correo>pepe@mail.com</correo>
        <telefono prefijo="+46">111222333</telefono>
    </contacto>

    <contacto>
        <nombre>Michael</nombre>
        <correo>mick@mail.com</correo>
        <telefono>555888222</telefono>
    </contacto>

    <contacto>
        <nombre>Raphael</nombre>
        <correo>raphael@mail.com</correo>
        <telefono prefijo="+44">555666333</telefono>
    </contacto>        
</agenda>

